//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstQuestionResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstQuestionResponse()
        {
            this.txnQuestionResponses = new HashSet<txnQuestionResponse>();
        }
    
        public int ResponseId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> SubTypeId { get; set; }
        public Nullable<int> ResponseNumber { get; set; }
        public string ResponseText { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual mstQuestion mstQuestion { get; set; }
        public virtual mstQuestionSubType mstQuestionSubType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestionResponse> txnQuestionResponses { get; set; }
    }
}
