//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstQuestionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstQuestionType()
        {
            this.mstQuestions = new HashSet<mstQuestion>();
            this.mstQuestionSubTypes = new HashSet<mstQuestionSubType>();
            this.txnQuestionResponses = new HashSet<txnQuestionResponse>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<int> SetId { get; set; }
    
        public virtual mstExamSet mstExamSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstQuestion> mstQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstQuestionSubType> mstQuestionSubTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestionResponse> txnQuestionResponses { get; set; }
    }
}
