//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstScoreModule
    {
        public int ScoreId { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<int> SubModuleId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual mstSubModule mstSubModule { get; set; }
    }
}
