//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuestionDemoEntities : DbContext
    {
        public QuestionDemoEntities()
            : base("name=QuestionDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mstExamSet> mstExamSets { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<mstAge> mstAges { get; set; }
        public virtual DbSet<MstConfig> MstConfigs { get; set; }
        public virtual DbSet<mstCountry> mstCountries { get; set; }
        public virtual DbSet<mstEmployeeStatu> mstEmployeeStatus { get; set; }
        public virtual DbSet<mstGender> mstGenders { get; set; }
        public virtual DbSet<mstIndustry> mstIndustries { get; set; }
        public virtual DbSet<mstMailConfig> mstMailConfigs { get; set; }
        public virtual DbSet<mstMaritalStatu> mstMaritalStatus { get; set; }
        public virtual DbSet<mstProfession> mstProfessions { get; set; }
        public virtual DbSet<mstProfileSelected> mstProfileSelecteds { get; set; }
        public virtual DbSet<mstQualification> mstQualifications { get; set; }
        public virtual DbSet<mstQuestion> mstQuestions { get; set; }
        public virtual DbSet<mstQuestionReponseType> mstQuestionReponseTypes { get; set; }
        public virtual DbSet<mstQuestionResponse> mstQuestionResponses { get; set; }
        public virtual DbSet<mstQuestionSubType> mstQuestionSubTypes { get; set; }
        public virtual DbSet<mstQuestionType> mstQuestionTypes { get; set; }
        public virtual DbSet<mstScoreModule> mstScoreModules { get; set; }
        public virtual DbSet<mstState> mstStates { get; set; }
        public virtual DbSet<mstSubModule> mstSubModules { get; set; }
        public virtual DbSet<txnAttachmentMailSent> txnAttachmentMailSents { get; set; }
        public virtual DbSet<txnExamSetStatu> txnExamSetStatus { get; set; }
        public virtual DbSet<txnIndustry> txnIndustries { get; set; }
        public virtual DbSet<txnQuesResponseWithSubModule> txnQuesResponseWithSubModules { get; set; }
        public virtual DbSet<txnQuestion> txnQuestions { get; set; }
        public virtual DbSet<txnQuestionResponse> txnQuestionResponses { get; set; }
        public virtual DbSet<txnUserTestDetail> txnUserTestDetails { get; set; }
        public virtual DbSet<txnCandidate> txnCandidates { get; set; }
        public virtual DbSet<mstMailType> mstMailTypes { get; set; }
    
        public virtual ObjectResult<usp_SubTypeWiseScoreBoard_Result> usp_SubTypeWiseScoreBoard(Nullable<int> testId, Nullable<int> sETID)
        {
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            var sETIDParameter = sETID.HasValue ?
                new ObjectParameter("SETID", sETID) :
                new ObjectParameter("SETID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SubTypeWiseScoreBoard_Result>("usp_SubTypeWiseScoreBoard", testIdParameter, sETIDParameter);
        }
    
        public virtual ObjectResult<usp_TypeWiseScoreBoard_Result> usp_TypeWiseScoreBoard(Nullable<int> testId, Nullable<int> sETId)
        {
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            var sETIdParameter = sETId.HasValue ?
                new ObjectParameter("SETId", sETId) :
                new ObjectParameter("SETId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TypeWiseScoreBoard_Result>("usp_TypeWiseScoreBoard", testIdParameter, sETIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_InsertRandomQuestion(Nullable<int> userId, Nullable<int> sETId, Nullable<int> testId, Nullable<int> tYPEID, string hostName, ObjectParameter testUniqId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var sETIdParameter = sETId.HasValue ?
                new ObjectParameter("SETId", sETId) :
                new ObjectParameter("SETId", typeof(int));
    
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            var tYPEIDParameter = tYPEID.HasValue ?
                new ObjectParameter("TYPEID", tYPEID) :
                new ObjectParameter("TYPEID", typeof(int));
    
            var hostNameParameter = hostName != null ?
                new ObjectParameter("HostName", hostName) :
                new ObjectParameter("HostName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_InsertRandomQuestion", userIdParameter, sETIdParameter, testIdParameter, tYPEIDParameter, hostNameParameter, testUniqId);
        }
    
        public virtual ObjectResult<usp_GetScoreCardName_Result1> usp_GetScoreCardName(Nullable<int> testId, Nullable<int> setId)
        {
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            var setIdParameter = setId.HasValue ?
                new ObjectParameter("SetId", setId) :
                new ObjectParameter("SetId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetScoreCardName_Result1>("usp_GetScoreCardName", testIdParameter, setIdParameter);
        }
    }
}
