//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnAttachmentMailSent
    {
        public int MailSentId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> MailSentFlg { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual txnUserTestDetail txnUserTestDetail { get; set; }
    }
}
