//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public txnCandidate()
        {
            this.txnIndustries = new HashSet<txnIndustry>();
            this.txnUserTestDetails = new HashSet<txnUserTestDetail>();
        }
    
        public int UserId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserEmail { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> UserGender { get; set; }
        public Nullable<int> UserAge { get; set; }
        public Nullable<int> UserState { get; set; }
        public Nullable<int> UserCountry { get; set; }
        public Nullable<int> UserQualification { get; set; }
        public Nullable<int> UserProfessional { get; set; }
        public Nullable<int> UserMaritalStatus { get; set; }
        public Nullable<int> UserEmployeeStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ProfileSelected { get; set; }
        public Nullable<bool> IsOTPRequire { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> IsInitialMail { get; set; }
        public Nullable<bool> IsAttachmentSent { get; set; }
        public string TransId { get; set; }
        public string TransStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnIndustry> txnIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnUserTestDetail> txnUserTestDetails { get; set; }
    }
}
