//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnIndustry
    {
        public int Id { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual mstIndustry mstIndustry { get; set; }
        public virtual txnCandidate txnCandidate { get; set; }
    }
}
