//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public txnQuestion()
        {
            this.txnQuestionResponses = new HashSet<txnQuestionResponse>();
        }
    
        public int TestQuestionId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> ImpactScore { get; set; }
        public Nullable<System.DateTime> ResponseAt { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> ResponseBy { get; set; }
        public Nullable<int> Setid { get; set; }
    
        public virtual mstExamSet mstExamSet { get; set; }
        public virtual mstQuestion mstQuestion { get; set; }
        public virtual txnUserTestDetail txnUserTestDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestionResponse> txnQuestionResponses { get; set; }
    }
}
