//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnQuesResponseWithSubModule
    {
        public int QResId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> SubModuleId { get; set; }
        public Nullable<int> SetId { get; set; }
        public Nullable<int> SumOfScore { get; set; }
        public Nullable<int> AvgOfScore { get; set; }
        public Nullable<int> calcuation { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual mstSubModule mstSubModule { get; set; }
        public virtual txnUserTestDetail txnUserTestDetail { get; set; }
    }
}
