//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DummyCandidateRecord
    {
        public int CandidateRecordId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> LinkGenerationId { get; set; }
        public string CandidateName { get; set; }
        public string CandidateEmail { get; set; }
    }
}
