//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_QMP_Normatives
    {
        public int CompetencyId { get; set; }
        public string CompeteciesName { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }
        public string Type3 { get; set; }
        public string Type4 { get; set; }
        public string Type5 { get; set; }
        public string Type6 { get; set; }
        public string Type7 { get; set; }
        public string Type8 { get; set; }
        public string Type9 { get; set; }
        public Nullable<int> TypeId { get; set; }
    }
}
