//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstHumanResourceRepo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstHumanResourceRepo()
        {
            this.txnHrMapToCompanyAndAssessments = new HashSet<txnHrMapToCompanyAndAssessment>();
            this.txnCandidates = new HashSet<txnCandidate>();
        }
    
        public int HrId { get; set; }
        public string HrName { get; set; }
        public string HrEmail { get; set; }
        public string HrPhoneNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnHrMapToCompanyAndAssessment> txnHrMapToCompanyAndAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnCandidate> txnCandidates { get; set; }
    }
}
