//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstMailTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstMailTemplate()
        {
            this.mstProfileSelecteds = new HashSet<mstProfileSelected>();
            this.mstProfileSelecteds1 = new HashSet<mstProfileSelected>();
            this.mst_mailConfigByAssessment = new HashSet<mst_mailConfigByAssessment>();
            this.mstmailConfigByAssessments = new HashSet<mstmailConfigByAssessment>();
            this.txnCandidateLinkHistories = new HashSet<txnCandidateLinkHistory>();
            this.txnCandidateLinkHistories1 = new HashSet<txnCandidateLinkHistory>();
            this.TxnLinkGenerationIds = new HashSet<TxnLinkGenerationId>();
            this.TxnLinkGenerationIds1 = new HashSet<TxnLinkGenerationId>();
        }
    
        public int MailTemplateId { get; set; }
        public string SMTP_SenderNAME { get; set; }
        public string SMTP_USERNAME { get; set; }
        public string SMTP_PASSWORD { get; set; }
        public string CONFIGSET { get; set; }
        public string FromMailAddress { get; set; }
        public string BCCMailAddress { get; set; }
        public string CCMailAddress { get; set; }
        public string HOST { get; set; }
        public string PORT { get; set; }
        public string BODY { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstProfileSelected> mstProfileSelecteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstProfileSelected> mstProfileSelecteds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_mailConfigByAssessment> mst_mailConfigByAssessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstmailConfigByAssessment> mstmailConfigByAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnCandidateLinkHistory> txnCandidateLinkHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnCandidateLinkHistory> txnCandidateLinkHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnLinkGenerationId> TxnLinkGenerationIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnLinkGenerationId> TxnLinkGenerationIds1 { get; set; }
    }
}
