//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstmailConfigByAssessment
    {
        public int MailConfigId { get; set; }
        public string MailType { get; set; }
        public string MailConfigName { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public Nullable<int> MailTemplateId { get; set; }
    
        public virtual mstAssessmentSet mstAssessmentSet { get; set; }
        public virtual mstMailTemplate mstMailTemplate { get; set; }
    }
}
