//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstProfileSelected
    {
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public Nullable<int> InitialMailSentId { get; set; }
        public Nullable<int> FinalMailSentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual mstMailTemplate mstMailTemplate { get; set; }
        public virtual mstMailTemplate mstMailTemplate1 { get; set; }
    }
}
