//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mstQuestion()
        {
            this.mstQuestionResponses = new HashSet<mstQuestionResponse>();
            this.txnQuestions = new HashSet<txnQuestion>();
            this.txnQuestionResponses = new HashSet<txnQuestionResponse>();
        }
    
        public int QuestionId { get; set; }
        public string Question { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SetId { get; set; }
        public Nullable<int> ResponseTypeId { get; set; }
        public Nullable<int> SubModuleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual mstQuestionReponseType mstQuestionReponseType { get; set; }
        public virtual mstQuestionType mstQuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mstQuestionResponse> mstQuestionResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestion> txnQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestionResponse> txnQuestionResponses { get; set; }
        public virtual mstAssessmentModule mstAssessmentModule { get; set; }
    }
}
