//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    
    public partial class Sp_ExportTypeWiseScoreCard_Result1
    {
        public string Type_Name { get; set; }
        public string Question { get; set; }
        public string Response_Value { get; set; }
        public Nullable<int> Score { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
    }
}
