//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnCampanyMapToAssessment
    {
        public int CoAsId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> isactive { get; set; }
    
        public virtual mstAssessmentSet mstAssessmentSet { get; set; }
        public virtual mstCompany mstCompany { get; set; }
    }
}
