//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnClusterMapToCompetency
    {
        public int ClusterMapToCompetencyId { get; set; }
        public Nullable<int> ClusterId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<int> Weightage { get; set; }
        public Nullable<int> WeightageScore { get; set; }
    
        public virtual mstCluster mstCluster { get; set; }
    }
}
