//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnConfigureMailSent
    {
        public int MailShootId { get; set; }
        public Nullable<int> LinkGenerationId { get; set; }
        public Nullable<bool> IsLinkSentToCandidate { get; set; }
        public Nullable<bool> IsLinkSentToHr { get; set; }
        public Nullable<bool> IsReportSentToCandidate { get; set; }
        public Nullable<bool> IsReportSentToHr { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string LastModifedBy { get; set; }
        public Nullable<System.DateTime> LastModifedAt { get; set; }
    
        public virtual TxnLinkGenerationId TxnLinkGenerationId { get; set; }
    }
}
