//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnCandidateLinkHistory
    {
        public int LinkHisId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> InitialMailTemplateId { get; set; }
        public Nullable<int> FinalMailTemplateId { get; set; }
        public Nullable<bool> ReportSendToHr { get; set; }
        public Nullable<bool> ReportSendToCandidate { get; set; }
    
        public virtual mstMailTemplate mstMailTemplate { get; set; }
        public virtual mstMailTemplate mstMailTemplate1 { get; set; }
        public virtual txnUserTestDetail txnUserTestDetail { get; set; }
    }
}
