//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnDynamicMisTyping
    {
        public int MisTypingId { get; set; }
        public string TypeA { get; set; }
        public string TypeB { get; set; }
        public string MisTypeName { get; set; }
        public Nullable<int> MisTypeId { get; set; }
        public Nullable<int> HighestType { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> Type { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<int> AssessmentId { get; set; }
    
        public virtual mstAssessmentSet mstAssessmentSet { get; set; }
        public virtual txnUserTestDetail txnUserTestDetail { get; set; }
    }
}
