//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnLinkGenerationId
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TxnLinkGenerationId()
        {
            this.TxnConfigureMailSents = new HashSet<TxnConfigureMailSent>();
        }
    
        public int LinkGenerationId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public Nullable<int> InitialMailId { get; set; }
        public Nullable<int> FinalMailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LastModifedAt { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual mstAssessmentSet mstAssessmentSet { get; set; }
        public virtual mstMailTemplate mstMailTemplate { get; set; }
        public virtual mstMailTemplate mstMailTemplate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnConfigureMailSent> TxnConfigureMailSents { get; set; }
        public virtual mstCompany mstCompany { get; set; }
    }
}
