//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnQuestionResponse
    {
        public int TestQuestionResponseId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> QuestionResponseId { get; set; }
        public Nullable<int> TxnQuestionId { get; set; }
        public int TestId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> SubTypeId { get; set; }
        public Nullable<int> impactscore { get; set; }
    
        public virtual mstQuestion mstQuestion { get; set; }
        public virtual mstQuestionResponse mstQuestionResponse { get; set; }
        public virtual mstQuestionType mstQuestionType { get; set; }
        public virtual txnQuestion txnQuestion { get; set; }
        public virtual txnUserTestDetail txnUserTestDetail { get; set; }
    }
}
