//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnUserTestDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public txnUserTestDetail()
        {
            this.txnDynamicMisTypings = new HashSet<txnDynamicMisTyping>();
            this.txnExamSetStatus = new HashSet<txnExamSetStatu>();
            this.txnQuestions = new HashSet<txnQuestion>();
            this.txnQuestionResponses = new HashSet<txnQuestionResponse>();
            this.txnCandidateLinkHistories = new HashSet<txnCandidateLinkHistory>();
        }
    
        public int TestId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> UserId { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnDynamicMisTyping> txnDynamicMisTypings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnExamSetStatu> txnExamSetStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestion> txnQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnQuestionResponse> txnQuestionResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<txnCandidateLinkHistory> txnCandidateLinkHistories { get; set; }
        public virtual txnCandidate txnCandidate { get; set; }
    }
}
