//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionWizardApi.CorporateData
{
    using System;
    
    public partial class usp_TypeWiseScoreBoard_Result1
    {
        public Nullable<int> ImpactScore { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string colorCode { get; set; }
    }
}
